---
- name: register current bbb properties
  become: true
  slurp:
    src: /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
  register: properties

- name: set bbb hostname
  command: "bbb-conf --setip {{ bbbackend__hostname }}"
  become: true
  when: properties['content'] | b64decode | regex_search(bbbackend__hostname, multiline=True, ignorecase=True) != bbbackend__hostname
  notify: restart bigbluebutton

- name: enable join via html5
  become: true
  lineinfile:
    path: /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
    regexp: '^attendeesJoinViaHTML5Client'
    line: 'attendeesJoinViaHTML5Client=true'
  notify: restart bigbluebutton

- name: enable mod join via html5
  become: true
  lineinfile:
    path: /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
    regexp: '^moderatorsJoinViaHTML5Client'
    line: 'moderatorsJoinViaHTML5Client=true'
  notify: restart bigbluebutton

- name: set bbb to use HTTPS
  become: true
  lineinfile:
    path: /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
    regexp: '^bigbluebutton.web.serverURL'
    line: 'bigbluebutton.web.serverURL=https://{{ bbbackend__hostname }}'
  notify: restart bigbluebutton

- name: set recording default
  become: true
  lineinfile:
    path: /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
    regexp: '^disableRecordingDefault'
    line: 'disableRecordingDefault={{ bbbackend__disable_recordings | ternary("true", "false") }}'
  notify: restart bigbluebutton

- name: ensure recording auto start is disabled
  become: true
  lineinfile:
    path: /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
    regexp: '^autoStartRecording'
    line: 'autoStartRecording=false'
  notify: restart bigbluebutton

- name: allow/disable users to start recordings
  become: true
  lineinfile:
    path: /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
    regexp: '^allowStartStopRecording'
    line: 'allowStartStopRecording={{ bbbackend__disable_recordings | ternary("false", "true") }}'
  notify: restart bigbluebutton

- name: set muteOnStart
  become: true
  lineinfile:
    path: /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
    regexp: '^muteOnStart'
    line: 'muteOnStart={{ bbbackend__mute_on_start | ternary("false", "true") }}'
  notify: restart bigbluebutton

- name: set appLogLevel
  become: true
  lineinfile:
    path: /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
    regexp: '^appLogLevel'
    line: 'appLogLevel={{ bbbackend__app_log_level }}'
  notify: restart bigbluebutton

- name: set red5 to use HTTPS 1/2
  become: true
  lineinfile:
    path: /usr/share/red5/webapps/screenshare/WEB-INF/screenshare.properties
    regexp: '^jnlpUrl'
    line: 'jnlpUrl=https://{{ bbbackend__hostname }}/screenshare'
  notify: restart bigbluebutton

- name: set red5 to use HTTPS 2/2
  become: true
  lineinfile:
    path: /usr/share/red5/webapps/screenshare/WEB-INF/screenshare.properties
    regexp: '^jnlpFile'
    line: 'jnlpFile=https://{{ bbbackend__hostname }}/screenshare/screenshare.jnlp'
  notify: restart bigbluebutton

- name: copy TURN config file
  become: true
  template:
    src: bbb/turn-stun-servers.xml.j2
    dest: /usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml
  notify: restart bigbluebutton

- name: serve recordings via https
  become: true
  lineinfile:
    path: /usr/local/bigbluebutton/core/scripts/bigbluebutton.yml
    regexp: "playback_protocol"
    line: "playback_protocol: https"
  notify: restart bigbluebutton

- name: set BigBlueButton client to load components via HTTPS
  become: true
  notify: restart bigbluebutton
  replace:
    path: /var/www/bigbluebutton/client/conf/config.xml
    regexp: 'http://'
    replace: 'https://'

- name: set note server to use HTTPS
  become: true
  notify: restart bigbluebutton
  replace:
    path: /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
    regexp: 'http://'
    replace: 'https://'

- name: set korrento server to use HTTPS
  become: true
  notify: restart bigbluebutton
  replace:
    path: /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
    regexp: 'ws://'
    replace: 'wss://'

- name: Read meteor
  become: true
  slurp:
    path: /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
  register: r_meteor

- name: extract config of meteor
  set_fact:
    meteor: "{{ r_meteor['content'] | b64decode | from_yaml }}"

- name: combine meteor config
  set_fact:
    meteor: "{{ meteor | combine(bbbackend__meteor, recursive=true) }}"

- name: write back new meteor config
  become: true
  notify: restart bigbluebutton
  copy:
    content: '{{ meteor  | to_nice_yaml }}'
    dest: /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml

- name: configure freeswitch to use SSL
  become: true
  lineinfile:
    path: /etc/bigbluebutton/nginx/sip.nginx
    regexp: "proxy_pass"
    line: "        proxy_pass https://{{ ansible_default_ipv4.address }}:7443;"
  notify: reload nginx

- name: create ssl folder for nginx
  become: true
  file:
    path: /etc/nginx/ssl
    state: directory
  when: bbbackend__nginx_dh

- name: Deploy DH Parameters with a different size (4096 bits)
  become: true
  copy:
    src: dhp-4096.pem
    dest: /etc/nginx/ssl/dhp-4096.pem
    owner: root
    group: root
    mode: '0644'
  notify: reload nginx
  when: bbbackend__nginx_dh

- name: copy bbb's nginx vhost
  become: true
  template:
     src: bbb/bigbluebutton.j2
     dest: /etc/nginx/sites-available/bigbluebutton
  notify: reload nginx

- name: enable CPUSchedulingPolicy in FreeSWITCH service
  become: true
  lineinfile:
    path: /lib/systemd/system/freeswitch.service
    regexp: '^#?CPUSchedulingPolicy=rr'
    line: 'CPUSchedulingPolicy=rr'
  notify:
  - restart freeswitch
  - reload systemd
  when: bbbackend__cpuschedule | bool

- name: disable CPUSchedulingPolicy in FreeSWITCH service
  become: true
  lineinfile:
    path: /lib/systemd/system/freeswitch.service
    regexp: '^#?CPUSchedulingPolicy=rr'
    line: '#CPUSchedulingPolicy=rr'
  notify:
  - freeswitch
  - reload systemd
  when: not bbbackend__cpuschedule | bool

- name: enable IPv6 in FreeSWITCH service 1/2
  become: true
  command:
    cmd: mv {{ item }}_ {{ item }}
    creates: "{{ item }}"
    removes: "{{ item }}_"
  with_items:
    - "/opt/freeswitch/etc/freeswitch/sip_profiles/internal-ipv6.xml"
    - "/opt/freeswitch/etc/freeswitch/sip_profiles/external-ipv6.xml"
  when: bbbackend__freeswitch_ipv6 | bool
  notify:
  - restart freeswitch
  - reload nginx

- name: enable IPv6 in FreeSWITCH service 2/2
  become: true
  lineinfile:
    path: /opt/freeswitch/etc/freeswitch/autoload_configs/event_socket.conf.xml
    regexp: '<param name="listen-ip" value="127.0.0.1"/>'
    line: '<param name="listen-ip" value="::"/>'
  when: bbbackend__freeswitch_ipv6 | bool
  notify:
  - restart freeswitch
  - reload nginx

- name: disable IPv6 in FreeSWITCH service 1/2
  become: true
  command:
    cmd: mv {{ item }} {{ item }}_
    creates: "{{ item }}_"
    removes: "{{ item }}"
  with_items:
    - "/opt/freeswitch/etc/freeswitch/sip_profiles/internal-ipv6.xml"
    - "/opt/freeswitch/etc/freeswitch/sip_profiles/external-ipv6.xml"
  when: not bbbackend__freeswitch_ipv6 | bool
  notify:
  - restart freeswitch
  - reload nginx

- name: disable IPv6 in FreeSWITCH service 2/2
  become: true
  lineinfile:
    path: /opt/freeswitch/etc/freeswitch/autoload_configs/event_socket.conf.xml
    regexp: '<param name="listen-ip" value="::"/>'
    line: '<param name="listen-ip" value="127.0.0.1"/>'
  when: not bbbackend__freeswitch_ipv6 | bool
  notify:
  - restart freeswitch
  - reload nginx

- name: FreeSWITCH dialplan quality
  become: true
  replace:
    path: /opt/freeswitch/conf/dialplan/default/bbb_conference.xml
    regexp: '<action application="conference" data="\$1@.*"\/>'
    replace: '<action application="conference" data="$1@{{ bbbackend__dialplan_quality }}"/>'
  notify:
  - restart freeswitch
  - reload nginx

- name: FreeSWITCH dialplan quality (echo)
  become: true
  replace:
    path: /opt/freeswitch/conf/dialplan/default/bbb_echo_to_conference.xml
    regexp: '<action application="conference" data="\${vbridge}@.*"\/>'
    replace: '<action application="conference" data="${vbridge}@{{ bbbackend__dialplan_quality }}"/>'
  notify:
  - restart freeswitch
  - reload nginx

- name: FreeSWITCH dialplan energy-level
  become: true
  replace:
    path: /opt/freeswitch/etc/freeswitch/autoload_configs/conference.conf.xml
    after: '<profile name="{{ bbbackend__dialplan_quality }}">'
    before: '</profile>'
    regexp: '<param name="energy-level" value=".*"\/>'
    replace: '<param name="energy-level" value="{{ bbbackend__dialplan_energy_level }}"/>'
  notify:
  - restart freeswitch
  - reload nginx

- name: FreeSWITCH dialplan comfort-noise
  become: true
  replace:
    path: /opt/freeswitch/etc/freeswitch/autoload_configs/conference.conf.xml
    after:   '<profile name="{{ bbbackend__dialplan_quality }}">'
    before:  '</profile>'
    regexp:  '<param name="comfort-noise" value=".*"\/>'
    replace: '<param name="comfort-noise" value="{{ bbbackend__dialplan_comfort_noise }}"/>'
  notify:
  - restart freeswitch
  - reload nginx

- name: FreeSWITCH external ip (rtp)
  become: true
  replace:
    path: /opt/freeswitch/etc/freeswitch/vars.xml
    regexp:  '<X-PRE-PROCESS cmd="set" data="external_rtp_ip=.*"\/>'
    replace: '<X-PRE-PROCESS cmd="set" data="external_rtp_ip={{ bbbackend__freeswitch_external_ip }}"/>'
  notify:
  - restart freeswitch
  - reload nginx

- name: FreeSWITCH external ip (sip)
  become: true
  replace:
    path: /opt/freeswitch/etc/freeswitch/vars.xml
    regexp:  '<X-PRE-PROCESS cmd="set" data="external_sip_ip=.*"\/>'
    replace: '<X-PRE-PROCESS cmd="set" data="external_sip_ip={{ bbbackend__freeswitch_external_ip }}"/>'
  notify:
  - restart freeswitch
  - reload nginx
