---
- name: LXD | disable freeswitch scheduling options
  become: true
  replace:
    dest: /lib/systemd/system/freeswitch.service
    regexp: "{{ item.re }}"
    replace: "{{ item.rep }}"
    backup: yes
    mode: '0644'
  with_items:
    - { re: '^IOSchedulingClass=realtime', rep: '#IOSchedulingClass=realtime' }
    - { re: '^CPUSchedulingPolicy=rr', rep: '#CPUSchedulingPolicy=rr' }
  notify:
    - reload systemd


