---
- name: install freeswitch-watchdog
  become: true
  apt:
    deb: "{{ bbbackend__freeswitch_watchdog_deb }}"

- name: Create the systemd service for freeswitch-watchdog
  become: true
  template:
    src: freeswitch-watchdog.service.j2
    dest: "/etc/systemd/system/freeswitch-watchdog.service"
    mode: '0644'
  notify: restart freeswitch-watchdog

- name: enable systemd service for freeswitch-watchdog
  become: true
  systemd:
    name: freeswitch-watchdog.service
    state: started
    enabled: true
    daemon_reload: true
