---
- include_tasks: packages.yml
  when: bbbackend__manage_packages | bool

- import_tasks: repositories.yml
  when: bbbackend__manage_repositories | bool

- name: install bbb and dependencies
  become: true
  apt:
    name: "{{ bbbackend__bbb_and_dependencies }}"
    state: "{{ bbbackend__state }}"

- import_tasks: freeswitch.yml

- meta: flush_handlers

- name: Ensure nginx is started and enabled to start at boot.
  service:
    name: nginx
    enabled: yes
    state: started
  become: true

- name: Check if bbbackend__ssl_cert exists
  stat:
    path: "{{ bbbackend__ssl_cert }}"
  register: bbbackbonecert

- import_tasks: letsencrypt.yml
  when: bbbackend__letsencrypt_enable and not bbbackbonecert.stat.exists

- import_tasks: certificate-selfsigned.yml
  when: not bbbackend__letsencrypt_enable and not bbbackbonecert.stat.exists

- import_tasks: config.yml

- import_tasks: freeswitch-watchdog.yml
  tags: [freeswitch-watchdog]

- import_tasks: coturn.yml
  when: bbb_coturn_enable
