---
- name: Install required packages
  apt:
    name: "{{ bbb_required_packages }}"
    update_cache: true
    state: "{{ bbb_state }}"

- name: set version of java to use
  file:
    src: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
    dest: /etc/alternatives/java
    state: link
  notify: restart bigbluebutton

- import_tasks: locale.yml

- import_tasks: repositories.yml

- name: install bbb and dependencies
  apt:
    name: "{{ bbb_and_dependencies }}"
    state: "{{ bbb_state }}"

- import_tasks: mongodb.yml

- name: LXD | disable freeswitch scheduling options
  replace:
    dest: /lib/systemd/system/freeswitch.service
    regexp: "{{ item.re }}"
    replace: "{{ item.rep }}"
    backup: yes
    mode: '0644'
  with_items:
    - { re: '^IOSchedulingClass=realtime', rep: '#IOSchedulingClass=realtime' }
    - { re: '^CPUSchedulingPolicy=rr', rep: '#CPUSchedulingPolicy=rr' }
  notify:
    - reload systemd

- meta: flush_handlers

- name: Ensure mongod is started and enabled to start at boot.
  service:
    name: mongod
    enabled: yes
    state: started

- name: Ensure nginx is started and enabled to start at boot.
  service:
    name: nginx
    enabled: yes
    state: started

- name: Check if bbb_ssl_cert exists
  stat:
    path: "{{ bbb_ssl_cert }}"
  register: bbbcert

- import_tasks: letsencrypt.yml
  when: bbb_letsencrypt_enable and not bbbcert.stat.exists

- import_tasks: certificate-selfsigned.yml
  when: not bbb_letsencrypt_enable and not bbbcert.stat.exists

- import_tasks: config.yml

- import_tasks: freeswitch-watchdog.yml
  tags: [freeswitch-watchdog]

- import_tasks: coturn.yml
  when: bbb_coturn_enable
