---
- name: Install required packages
  become: true
  apt:
    name: "{{ bbbackend__required_packages }}"
    update_cache: true
    state: "{{ bbbackend__state }}"

- name: set version of java to use
  become: true
  file:
    src: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
    dest: /etc/alternatives/java
    state: link
  notify: restart bigbluebutton
