---
- name: add BigBlueButton apt key
  become: true
  apt_key:
    url: "{{ bbbackend__apt_mirror }}/repo/bigbluebutton.asc"
    id: '{{ bbbackend__apt_key }}'
    state: present

- name: add multiverse apt repositories
  become: true
  apt_repository:
    repo: "{{ item }}"
    state: present
    mode: '0644'
  with_items:
    - "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release | lower }} multiverse"
    - "deb-src http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release | lower }} multiverse"
    - "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release | lower }}-updates multiverse"
    - "deb-src http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release | lower }}-updates multiverse"

- name: add Xenial dependency apt repositories
  become: true
  apt_repository:
    repo: "{{ item }}"
    state: present
    mode: '0644'
  when: ansible_distribution_release == 'xenial'
  with_items:
    - ppa:bigbluebutton/support
    - ppa:rmescandon/yq

- name: add dependency apt repositories
  become: true
  apt_repository:
    repo: "{{ item }}"
    state: present
    mode: '0644'
  with_items:
    - "deb {{ bbbackend__apt_mirror }}/xenial-22/ bigbluebutton-xenial main"
  when: ansible_distribution_release == 'xenial'
