---
- name: reload nginx
  become: true
  service:
    name: nginx
    state: reloaded

- name: restart nginx
  service:
    name: nginx
    state: restarted

- name: restart bigbluebutton
  command: bbb-conf --restart
  become: true

- name: restart freeswitch
  systemd:
    name: freeswitch
    state: restarted
  become: true

- name: restart freeswitch-watchdog
  service:
    name: freeswitch-watchdog
    state: restarted
  become: true

- name: reload systemd
  become: true
  systemd:
    daemon_reload: true
